apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deployment
  namespace: lesson4
  labels:
    app: net
spec:
  replicas: 3
  selector:
    matchLabels:
      app: net
  template:
    metadata:
      labels:
        app: net
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: ngport
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: mtport
