apiVersion: v1
kind: Service
metadata:
  name: ngnet
  namespace: lesson4
spec:
  ports:
    - name: ngport
      port: 9001
      targetPort: 80
    - name: mtport
      port: 9002
      targetPort: 8080
  selector:
    app: net
