apiVersion: v1
kind: Service
metadata:
  name: ngnet2
  namespace: lesson4
spec:
  ports:
    - name: ngport
      port: 9001
      targetPort: 80
      nodePort: 30901
  selector:
    app: net
  type: NodePort
