apiVersion: v1
kind: Service
metadata:
  name: net-hello
spec:
  ports:
  - port: 80
  selector:
    app: hello-world
---
apiVersion: v1
kind: Service
metadata:
  name: net-netology
spec:
  ports:
  - port: 80
  selector: 
    app: netology-web
---
apiVersion: v1
kind: Service
metadata:
  name: net-curl
spec:
  ports:
  - port: 80
  selector: 
    app: curlpod
