apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: lesson5
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: ngport
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: lesson5
  labels:
    app: mttool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mttool
  template:
    metadata:
      labels:
        app: mttool
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: mtport
