apiVersion: v1
kind: Service
metadata:
  name: ngnet
  namespace: lesson5
spec:
  ports:
    - name: ngport
      port: 9001
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mtnet
  namespace: lesson5
spec:
  ports:
    - name: mtport
      port: 9002
      targetPort: 8080
  selector:
    app: mttool
