apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lesson3
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: ngport
      initContainers:
      - name: waiting
        image: busybox
        command: ['sh', '-c', "until nslookup ngnet.lesson3.svc.cluster.local; do sleep 2; done"]
