apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: lesson3
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: ngport
      - name: multitool
        image: wbitt/network-multitool
        env:
          - name: HTTP_PORT
            value: "31080"
        ports:
        - containerPort: 31080
          name: mtport
