apiVersion: v1
kind: Service
metadata:
  name: ngnet
  namespace: lesson3
spec:
  ports:
    - name: ngport
      port: 80
      targetPort: 80
    - name: mtport
      port: 31080
      targetPort: 31080
  selector:
    app: nginx
