apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-deployment
  namespace: lesson8
  labels:
    app: net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: net
  template:
    metadata:
      labels:
        app: net
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: default-cfg-volume
          mountPath: /etc/nginx/conf.d
        - name: ssl
          mountPath: /etc/ssl
        ports:
        - containerPort: 443
          name: ngport
      volumes:
      - name: html-volume
        configMap:
          name: htmlmap
      - name: default-cfg-volume
        configMap:
          name: confmap
      - name: ssl
        secret:
          secretName: cert
