apiVersion: v1
kind: PersistentVolume
metadata:
  name: local1
  namespace: lesson7
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
 # persistentVolumeReclaimPolicy: Delete
 # storageClassName: local-storage
  hostPath:
    path: /Users/jullmaksimova/homework/localtest
